DEAP/deap

doc/tutorials/basic/part4.rst
found another occurrence of the old link...
=> SCOOP link changed

deap/algorithms.py, deap/base.py, deap/cma.py, deap/creator.py, deap/gp.py, doc/api/algo.rst, doc/contributing.rst, doc/overview.rst
Attempt to clean up a bunch of problems reported with flake8.  I have broken them up into logical changes so that they are easier to review.  There are still problems reported, but nowhere near as many.
=> Miscellaneous changes

deap/benchmarks/__init__.py
Adding DTLZ5, DTLZ6, DTLZ7 and problem "Dent".
=> Mop problems

examples/ga/onemax.py
added more comments to examples/ga/onemax.py to make the code easier to understand for beginners 
(like me). No code changes.
=> added comments to examples/ga/onemax.py

.travis.yml
This PR allows deap to pass on travis-ci.
=> fix: pass travis-ci on pypy

doc/examples/ga_onemax.rst, examples/ga/onemax.py
Updates the code line references in the documentation. Not a final solution, perhaps, but it fixes the website.
=> Update code line references. Fixes #99

deap/tools/selection.py
It is an implementation of the [Stochastic Universal Sampling](https://en.wikipedia.org/wiki/Stochastic_universal_sampling) selection technique.
=> Added stochastic universal sampling selection method

README.md
=> Fixing typo in README: fell -> tell.

deap/tests/test_algorithms.py, deap/tools/constraint.py, examples/es/cma_mo.py
Add check in test and example to verify the final population is close to bounds.
Increase penalty factor (alpha) to 1.e6, to help guide the individuals back in bounds.
Decreased Hypervolume threshold for test. Now that the final solution is
valid, the resulting hypervolume is no longer consistently high.
=> Fix ClosestValidPenalty to use distance

deap/cma.py, deap/creator.py, deap/gp.py
cma.py:141:25: W503 line break before binary operator
cma.py:145:23: W503 line break before binary operator
cma.py:156:19: W503 line break before binary operator
cma.py:162:33: W503 line break before binary operator
gp.py:296:16: E713 test for membership should be 'not in'
gp.py:301:32: E713 test for membership should be 'not in'
gp.py:389:12: E713 test for membership should be 'not in'
gp.py:1027:5: E731 do not assign a lambda expression, use a def
gp.py:1074:9: E731 do not assign a lambda expression, use a def
gp.py:1082:9: E731 do not assign a lambda expression, use a def
gp.py:1083:9: E731 do not assign a lambda expression, use a def
=> Fix these flake8 warnings:

doc/examples/ga_onemax.rst, doc/examples/ga_onemax_short.rst, doc/tutorials/advanced/gp.rst, examples/ga/onemax.py
Hey,
I just started digging into the DEAP package today but was not really satisfied with the quality of the **One Max Example**. So I decided to rewrite it. Hope you like it. :)
I applied a minor change to the underlying python code. I don't really get why to run the evolution a predefined number of times. So I decided to use a while loop instead and terminate it as soon as one individual of the population reaches the desired One Max property.
It's also the first time ever I handled .rst files (not a python native). So I hope I got all the highlighting etc. right.
Cheers
=> One Max example

deap/tools/emo.py
selTournamentDCD presently has an implicit assumption (expressed in the comments) that the individuals length is a multiple of 4. This commit adds an explicit check for this and raises an exception on failure. 
**The addition is just after line 158**
```
if len(individuals)%4 !=0:
raise Exception("selTournamentDCD: individuals length must be a multiple of 4")
```
The changelog is messy because my editor automatically removed all trailing whitespace (as per PEP8)
When NSGA2.py has MU (population) set to, for example, 10 the previous error given was:
```
File "...", line 184, in selTournamentDCD
chosen.append(tourn(individuals_1[i+2], individuals_1[i+3]))
IndexError: list index out of range
```
New error:
```
File "....", line 161, in selTournamentDCD
raise Exception("selTournamentDCD: …
```
=> Improved error checking in selTournamentDCD

examples/pso/basic.py, examples/pso/basic_numpy.py
I've fixed the issue I posted: Speed clamping in PSO update example doesn't work properly #335. 
Please review the fix.
=> fix the open issue 335 for updateParticle in PSO example created by me

.travis.yml, deap/tests/test_init.py, deap/tests/test_logbook.py, deap/tests/test_statistics.py, deap/tools/init.py, deap/tools/support.py
Add doctests to nose testing in travis-ci
=> Add doctests

deap/gp.py, deap/tools/crossover.py, deap/tools/mutation.py
@Cirius1792 and I implemented both semantic mutation and crossover in order to allow users to execute a geometric semantic genetic programming instance by using GP and the semantic operators in the toolbox.
=> Implementation of the Geometric Semantic Genetic Programming operators

.travis.yml, setup.cfg
=> [MRG] Add flake8 to travis test

examples/ga/onemax_numpy.py
=> Fix comment typo "numpy.array((5.6.7.8))" -> "numpy.array((5,6,7,8))"

doc/index.rst
pyscoop.org is not a registered domain
=> fix broken SCOOP link

doc/examples/gp_symbreg.rst, doc/overview.rst, doc/tutorials/advanced/gp.rst, doc/tutorials/basic/part1.rst, doc/tutorials/basic/part2.rst
Want to thank you for an awsome GP framework!  Loved going through the tutorials. Found a few document enhancements that I'd like to propose. Please let me know if you'd like me to polish/change any of these.
Thanks!
=> A few doc updates

deap/tools/support.py
First element of the population is inserted twice when the HallOfFame is empty. 
I propose to insert the if inside the for loop, so the first element would be inserted automatically if the HallOfFame is empty and the loop will continue with the following element instead of repeating the first one.
Thank you!
=> fix: first element of the pop is inserted twice

deap/algorithms.py, deap/gp.py, doc/examples/gp_symbreg.rst
- A few doc updates (typos and re-wording)
- A few docstring typo fixes within `gp.py` and `algorithms.py`
=> Doc updates and Docstring typo fixes

deap/base.py, deap/cma.py, deap/creator.py, deap/gp.py, deap/tools/crossover.py, deap/tools/emo.py, deap/tools/mutation.py, deap/tools/support.py, doc/examples/gp_symbreg.rst
- A few docstring updates.
- One documentation update for Symbolic Regression example.
=> Docstring updates

deap/base.py
This check can make many careless errors visible.
=> feat(base.py.Fitness): check whether len(values) == len(weights)

deap/tools/init.py
Update documentation for deap.tools.initRepeat()
=> Update documentation for deap.tools.initRepeat()

azure-pipelines.yml
Added aarch64 wheel support.
Related to #558. @fmder Please review the changes.
=> Add aarch64 wheel support

doc/examples/gp_symbreg.rst
Make pronouns inclusive to non-males.
=> Update gendered language

doc/examples/gp_symbreg.rst
=> Fixed Typo

doc/tutorials/advanced/gp.rst
Add a sentence at the beginning of the "Plotting Trees" section explaining that a simple string representation of the tree/function can be obtained with `print`. 
The plotting has been finicky to get working right. This just notes that the easiest way to "visualize"  the function is to print out the candidate solution to see its string.
=> :memo: GP Print out candidate solutions

.gitignore
Adding intellij and vscode files to gitignore.
=> :memo: Add IDE stuff to gitignore

INSTALL.txt
Tiny change. 
Corrected a typo in "adding".
=> INSTALL typo --- addind -> adding

examples/gp/adf_symbreg.py
=> Remove unsued variable

.gitignore
Add virtual env folder to gitignore. 
I could add all the various stuff from [here](https://raw.githubusercontent.com/github/gitignore/main/Python.gitignore) too if preferrable.
=> gitignore Add venv to gitignore

doc/code/tutorials/part_2/2_2_5_particle.py, doc/tutorials/basic/part1.rst
Fixing some minor issues with the documentation in and around Particles and Swarms in the Tutorial and a Python 3 fix for xrange -> range in the swarm example.
=> Fixing issues with Particle and Swarm examples in basic tutorials.

deap/cma.py, examples/es/cma_mo.py, examples/gp/parity.py
=> Fix spelling errors found with codespell

README-zh_CN.md, README.md
Hi, I have created a Chinese translation for your README file. The corresponding terms have been translated in a way that is familiar to Chinese developers, and some words that Chinese developers are accustomed to using in English have not been awkwardly translated. This is a fantastic project, and I have recently been using genetic algorithms along with your project. There are many developers in China, and I hope that by adding a Chinese version of the README, more Chinese developers will learn about this project and appreciate it.
Thanks.
=> Add README-zh_CN.md file

.azure-pipelines/cd.yml, .azure-pipelines/ci.yml, deap/__init__.py
Removed out of life python and added new macOS environments.
=> Update deployment environments
