DEAP/deap

doc/conf.py
I find the docs for some functions(for instance the alpha parameter of cxBlend) difficult to understand, while the source is quite straightforward.  This commit adds the viewcode extension to the sphinx docs
=> Sphinx-generated docs should have view-source option

doc/tutorials/advanced/constraints.rst
Pretty obvious fixes.  Of greater concern is that the misspelling of 'penalty' ('penality') exists in class and function names and will be harder to fix. All other instances (eg in doco) can and should be fixed.
=> Typo fixes.

doc/installation.rst
`pip deap` doesn't work, but `pip install deap` does
=> Fix pip install command

setup.py
I've just tried to perform `pip install deap` on an ArchLinux system using Anaconda 3, and it crashed saying:
warning: pypandoc module not found, could not convert Markdown to RST
Traceback (most recent call last):
File "<string>", line 20, in <module>
File "/tmp/pip-build-5xgtngz9/deap/setup.py", line 22, in <module>
long_description=read_md('README.md'),
File "/tmp/pip-build-5xgtngz9/deap/setup.py", line 13, in <lambda>
read_md = lambda f: open(f, 'r').read()
File "/root/anaconda3/lib/python3.4/encodings/ascii.py", line 26, in decode
return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4945: ordinal not in range(128)
The same occured when trying the `master` version of the git repository.
Here's a fix provided. Should …
=> Fixed reading of UTF-8 files in setup.py

deap/cma.py
The reference to the paper where the implementation of CMA is detailed apears in the [cma-es example](https://deap.readthedocs.org/en/master/examples/cmaes.html), but not in the class docstring. Thus, when looking at the [cma strategies api documentation](https://deap.readthedocs.org/en/master/api/algo.html#module-deap.cma), the relevant reference cannot be found.
I added the citation in the docstrings  of the cma strategy classes, so that this would fix #132.
=> Include reference to paper in cma.Strategy and cma.StrategyOnePlusLambda

deap/tools/constraint.py
This enhancement is relative to the discussion on how handling constraints (https://github.com/DEAP/deap/issues/30). My point was more particularly on how to set a distance fonction abble to return penalties different for each fitness if we consider here not only constraints on inputs but also constraints on fitnesses. So, the idea here is to manage the fact that the distance should always be a tuple with a single element repeated (as many times as there are fitnesses) or diferent values for each fitnness.
=> dist as a tuple possibly different for each fitness instead of a sinle element applied to all

.travis.yml, deap/algorithms.py, deap/base.py, deap/benchmarks/binary.py, deap/tests/test_algorithms.py, deap/tests/test_benchmarks.py, deap/tests/test_creator.py, deap/tests/test_logbook.py, deap/tests/test_pickle.py, setup.py
A difference in integer division from python2 to python3 causes error when using bin2float.
In python2: `3/2` is `1` and in python3 `3/2` is `1.5`. The latter causes:
`TypeError: can't multiply sequence by non-int of type 'float'` in `in wrapped_function decoded = [0] * nelem`.
This pull request fix this error making this decorator usable in both python2 and 3.
This pull request also creates a test file for the benchmarks module.
Other files were also changed to comply with pep8.
=> Fixed bin2float behavior and added test suite for benchamarks.py

deap/tools/selection.py, examples/ga/mo_rhv.py
The selection tools are very convenient tools, but they could be made a bit more general if one could say which attribute of an individual to choose from.
Possible use cases are IBEA or HypE algorithms where an indicator function is used as an additional "fitness". With this patch request, the available selection tools could also be used for such cases.
=> Adapt selectors to use choosable attributes as criterion

deap/tools/support.py
Skip "ind is dominated by hofer" check if it dominates one of them already.
See https://github.com/DEAP/deap/issues/189.
I removed the `has_twin` condition from my proposal:
```
- if not dominates_one and not has_twin and hofer.fitness.dominates(ind.fitness):
+ if not dominates_one and hofer.fitness.dominates(ind.fitness):
```
because a twin may be dominated so this was abusive.
=> ParetoFront: skip useless domination tests in update()

deap/benchmarks/__init__.py
dtlz7 function used to raise ``TypeError: 'float' object has no attribute
'__getitem__'`` on each call.
Problem rose, because the same variable name ``ind`` was used both to
store coordinates of the individual and as a temporal variable in a loop.
Temporal variable used to override the original one used to store coordinates
of the individual. Problem fixed by using different name for the temporal variable.
=> Fix dtlz7 benchmark problem implementation

deap/tools/support.py
Sometimes it's useful to filter out a set of individuals and then updating the HoF with them. In that filtering process, it could be possible to end up with no individuals.
Nonetheless, when trying to update an empty HoF with an empty sequence as input, an IndexError would be raised because it would try to access a nonexistent zeroth element. I think that this is not an intuitive behaviour, as the HoF should have no problem dealing with an empty population update.
This simple check could avoid having to check if the population is empty every single time in user code.
=> Added support for empty population in HallOfFame.update

deap/benchmarks/binary.py
The usage of royal_road1 in royal_road2 is wrong because the order of parameters is reversed.
Now fix it.
=> exchange the position of individual and norder in binary.royal_road2

deap/tools/init.py
=> Fix typos in comments.

deap/tools/crossover.py
Make cxESTwoPoints call cxESTwoPoint instead of itself, avoiding infinite recursion.
=> Make cxESTwoPoints call cxESTwoPoint instead of itself.

deap/tools/emo.py
Now, if number of individuals to select(stored in parameter `k`) is not multiple of 4, it will throw. In addition, throw `ValueError` instead of generic `Exception` when input is invalid.
=> chore & fix(deap/tools/emo.py:selTournamentDCD): check on value of k & throw ValueError for failed input validation

setup.py
`setup.py` of this PR installs `numpy` if it is not available during the installation process of `deap`.
Now that [`deap.tools.indicator`](https://github.com/toshihikoyanase/deap/blob/d9608eabaf6e5234bd9140f41118cee6220a2c60/deap/tools/indicator.py#L17) depends on `numpy`,  users who installed only deap will encounter `ImportError` when they try to import `deap.tools` as follows:
```shell
>>> from deap import tools
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "deap/tools/__init__.py", line 26, in <module>
from .indicator import *
File "deap/tools/indicator.py", line 17, in <module>
import numpy
ImportError: No module named numpy
```
And some other files such as `deap.tools.constraint` and `deap.tools.selection.py` also require `numpy`.
=> Add numpy to installation requirements.

deap/tools/support.py, doc/releases.rst
All instances of the wrongly typed word "dictionnary" have been corrected by this PR.
=> fix typo "dictionnary" -> "dictionary"

deap/benchmarks/tools.py
The function itertools.repeat in bound.__init__ was called using 'itertools.repeat', while the function was imported using 'from itertools import repeat'.
=> Incorrect usage of itertools.repeat

setup.py
As per the title.
Discovered by accident in a clean build environment which did not yet have setuptools.
=> setup.py: Fix typo disutils -> distutils

deap/algorithms.py
This fixes #450 by appending the second child to offspring and controlling offspring length. In my use case it also increases speed for big populations quite a bit
=> Keep both crossover offspring in VarOr()

deap/tools/emo.py
The fix made in #347 seems to be incorrect. 
It is not the case that k and len(individuals) must be divisible by 4. Rather k only needs to be divisible by four if k == len(individuals).
Additionally, k must be <= len(individuals) to avoid going out of bounds when indexing. 
This fix keeps the error checking correct while allowing us to use selTournamentDCD on an arbitrary number of individuals.
=> Fix error checking in selTournamentDCD

doc/conf.py
html_sidebars dict values must now be a list.
Resolves a TemplateNotFound exception raised when building the documentation
with sphinx 2.4, as encountered when building the Debian packages.
http://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_sidebars
=> Adapt conf.py for sphinx >= 2.0

deap/tools/emo.py
https://github.com/DEAP/deap/issues/453
Fix the docstring of `isDominated` funciton.
As far as the code described below is concerned, when all `wvalues2`'s value are greater than all `wvalues1`'s ones, this function returns `True`.
```
elif self_wvalue < other_wvalue:
not_equal = True
return not_equal
```
I suppose it is the opposite of the current docstring description.
I also think the current description below is correct.
```
:returns: :obj:`True` if wvalues2 dominates wvalues1, :obj:`False`
otherwise.
```
This is my first pull request for Deap.
I would appreciate it if you review it, and let me know if you find any problems on this pull request.
Thank you very much!
=> Fix the docstring of isDominated function

deap/benchmarks/tools.py
Hey there. First of all thank you for your excellent work.
I've noticed that the [NSGA3 example](https://github.com/DEAP/deap/blob/master/examples/ga/nsga3.py) didn't work on my machine and it was due to a error I would get when calling `deap.benchmarks.tools.igd()` which requires a global variable called `scipy`. 
This variable doesn't exist if the `scipy` import is successful.
I have added the fix and renamed the variables for checking imports of `scipy` and `numpy` to avoid collisions (and confusion) with the original module names.
=> Fix: scipy and numpy import error for nsga-3 example

doc/examples/nsga3.rst
There is a small typo in doc/examples/nsga3.rst.
Should read `interested` rather than `interrested`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, interrested -> interested

deap/algorithms.py, deap/tools/constraint.py, deap/tools/mutation.py
Precisely what the title says. Avoids invalid escape sequence related warnings in Python 3.7 and onwards. See https://lwn.net/Articles/795546/ for further reference.
=> Use raw docstrings when LaTex is embedded

deap/tools/emo.py
I had an issue with a division by zero in the find_intercepts function (https://github.com/DEAP/deap/issues/534).
Apparently this is caused by numpy.linalg.solve which sometimes does not detect the singularity of the input matrix and thus does not throw an exception (https://github.com/numpy/numpy/issues/10471).
This pull request would fix this issue by detecting solutions with zeros.
=> Fix divided by zero in selNSGA3

doc/conf.py
Running with Sphinx under Python 3 was crashing with:
> There is a syntax error in your configuration file: (unicode error) 'unicodeescape' codec can't decode bytes in position 0-1: truncated \uXXXX escape (conf.py, line 246)
=> Escape \ in latex_preamble

deap/benchmarks/__init__.py
This is a minor fix which rectifies a typo in the docstring for `deap.benchmarks.rastrigin_scaled`. On the website, note the extra x^2 in the formatted equation:
=> fixed extra x^2 in docstring of rastrigin_scaled

deap/benchmarks/__init__.py
Minor fix where an addition sign is missing in the formatted equation written in the docstring.
=> fixed typo in docstring of rastrigin_skew benchmark function

README.md
Add a note to the readme's requirement section to discuss using `setuptools<=58` to accommodate `2to3`.
=> README `setuptools` version for `2to3`

deap/tests/test_mutation.py, deap/tools/mutation.py
Closes #592 
Adds an inversion mutation. See #592. Basically, select two points and reverse the order between the points. It's handy for when adjacency is really important as it ends up being less destructive (if that's what you're looking for). 
Notes:
- It is possible that the indices are the same or adjacent. This scenario is ignored and results in an unmodified individual
- The function was tested locally, but there are no unit test provided. I am not seeing any unit tests for any other genetic operators 
- The `end_point` is **not** selected with `random.randrange(start_index, size)` as that provides a different distribution of selected indices, which is bad. 
- I originally wrote the swapping with slicing, but thought it was too ugly.
=> Inversion Mutation

deap/tools/emo.py
Hi all,
I've encountered this division-by-zero warning in this line, which can be easily fixed with an epislon added to the denominator. The numpy choice will guarantee that it's using the smallest possible for the working machine.
Cheers
=> a simple division by zero fix

deap/gp.py
Should close #671, though further testing for 2->3 changes might be suggested throughout DEAP
=> Update compileADF in gp.py to work with python3

doc/tutorials/advanced/checkpoint.rst
The docs shows an example of saving in binary mode but then opening not using python's binary mode. This causes an error to be thrown when opening the file.
Fixes #489, Fixes #657 
The example below shows using pickle to save a dictionary in `wb` mode and load it in both `rb` and `r` mode. The `rb` move value will load correctly whereas the `r` mode load will not.
```python
import pickle
data = dict(firstValue=1, secondValue = "Example value")
with open("docsIssue.pkl", "wb") as file:
pickle.dump(data, file)
with open("docsIssue.pkl", "rb") as file:
loadedDatarb = pickle.load(file)
print("loadedData using rb mode", loadedDatarb)
with open("docsIssue.pkl", "r") as file:
loadedDatar = pickle.load(file)
print("loadedData using r mode", loadedDatar)
```
=> Switch read to use binary mode in Checkpoint example

MANIFEST.in
Congratulations on `1.4.0`!
This restores the `tests` to the `sdist`, which helps for downstreams such as https://github.com/conda-forge/deap-feedstock/pull/22.
A near term helpful fix so we can get 1.4.0 out would be to create https://github.com/DEAP/deap/releases/tag/1.4.0 so that the GitHub tarball at least has a predictable URL (and _sorta_ reproducible SHA256) until a release which contains the `tests` is made.
=> Include tests in sdist

doc/index.rst
The quote used currently is breaking the visualization of the documentation.
=> Fix quote that break documentation visualization

deap/gp.py
#733 already exists which is a fix for #732 but the PR is stale as code review changes were not addressed for 6+ months. This is an attempt to fix that. We were experimenting with `deap` to understand `gp` which is when we discovered this bug and saw it was already an issue. However before the fix, issue was closed.
This PR fixes #732 
Please review @cyrilpic @professor @bollwyvl @jmmcd @keszybz @fmder 
I didn't know exactly who to tag. That's y I tagged everyone.
=> Changes in python's random module require a minor change for `cxOnePointLeafBiased`.
